language: scala
jdk: oraclejdk8
scala:
- 2.11.5
script:
- mvn --settings ./target/settings.xml clean deploy
before_install:
- if [ -d target ]; then rm -rf target ; fi
- mkdir target
- openssl aes-256-cbc -K $encrypted_caf3ddac1184_key -iv $encrypted_caf3ddac1184_iv
  -in settings.xml.enc -out ./target/settings.xml -d
notifications:
  slack: ihealthtechnologies:0y49iFiXZjQyfDpHHWtgyswN#nexgen-build
env:
  global:
  - secure: X/L++T2H17tXtH1XA+yTtMrqUDGMTvdssGScFxWSMVHQoukT0LevI+lsKnfdFViMgJnWiqMLxFJP8U2XG7HkzK742Hz/C2O23LnUhvdxXh3VMsz8ch091PAyRF4reOcKbhVviFPxBLK+J98aYNQZapn1tM2BrzM8Fb+XpiNFbHg=
  - secure: LLhG7elntHEzhtrR/5rsJQhmQL0do1JQUYycSEckqSmpClcbAs2K1foUeBidtuxAoUUBWBHm7KL7THOsdWwPQZIoXCXR8v2gNasrua8l8Y+wcSWRqTK305D3+KIRbq3WTMw8V3LxlY8m5GuvcmAI9XdWOR0OLonzPxfFFgIkPDw=
  - secure: f/3fWorx9d/6O0WMvJGX8HXfD1FflKCT21WpnU56+OZAYthajNrAGo/WbmnO0/GsaofihbyxgNqPiDMH6EkocjZsA4LVZGFXe5zx+lqB/QZNXAgxNF6UeuznLsg8fanUnInvv56GIMWsX496YZEEFHpzW45vC3FgS0lE6llW8mo=
  - secure: dW7BjthB2ENcNIh/W51hweme2x98XXR5gbQ8ORQoJ8cOmOk887O8iQPpHnB7LpBk0d0jOuOWpxe25uKiPM5Hxtdf89HC0rDD3idA5OwlM29sME/0J73AHp3C0ESZuaNpO+xN/1kyqPurGHPeYyJXnq2aaOlC+PItXB4TA+YbiPM=
  - secure: JBDv4hjOCUUKeAO/YFapOduDjIlZ0+4gp3IMa2t0G+Mf5y0C0N2zVPHEtE0ajoPe5UvK97ME966s29LZKdJF+rTCDpSs9h0IWYqzKOtPQAaHoN/3pB1UcGcygehZpEKMUcoht0k8z1ndIu3sABrlGN0UUBPcVSvI/RPb0z3NFSw=
